### ISSUE TITLE
AIMA4e reimplement Chp 4 Onine search problem from AIMA3e branch

### ISSUE THREAD

**Issue by ctjoreilly** [aimacode/aima-java#131]

**Comment by paarandika** [comment]
I would like to work on this issue. Is there any differences between 3e and 4e algorithm wise? Or is it re implementing same thing?

**Comment by smsubham** [comment]
Hi
 AIMA4e branch is in progress , complete rewrite of the algorithms, leveraging JDK 8's new language features, from the AIMA3e branch. Algorithm would be same i suppose. Some part of AIMA4e is already implemented by @ctjoreilly  sir , i would recommend you to compare those implementation across AIMA3e and AIMA4e branch. @paarandika 

Regards
Subham

**Comment by BenK10** [comment]
Well, there's another issue here. it looks like the AIMA4e branch also has differences in the core search and agent APIs. Without knowing about the design decisions behind that and whether they are complete, I'm not sure I can correctly implement any of the desired algorithms. In other words, it looks like there is more to it than just updating the algorithm itself to Java 8.

There is an open issue for adding a wiki for AIMA4e. That wiki would be the place to write about this.

**Comment by BenK10** [comment]
Actually, I'm not sure there needs to be a separate OnlineSearchProblem for 4e because the Problem interface for 4e already supports all the behavior that 3e's OnlineSearchProblem has. In other words, since Problem is now more general than it used to be (compare 3e and 4e versions), it looks to me like you can use BasicProblem's implementation of it for an online problem, too. Or am I missing something?

**Comment by ctjoreilly** [comment]
Have refactored the Problem interface to now be an aggregate of 5 explicit functional interfaces. The two variants of the Problem interface, NondeterministicProblem and OnlineSearchProblem aggregate their appropriate sets of functional interfaces. The BasicProblem implementation implements support for all 3 variants.
