### ISSUE TITLE
AIMA4e reimplement Fig 6.5 Backtracking-Search from AIMA3e branch

### ISSUE THREAD

**Issue by ctjoreilly** [aimacode/aima-java#139]

**Comment by yatna** [comment]
Is this issue still open ?

**Comment by ctjoreilly** [comment]
Yes, though we are still working on stabilizing our APIs on the 4e branch.

**Comment by yatna** [comment]
@ctjoreilly I am really interested in contributing . Can you point out some beginners issue , so that I may get started. I have set up the environment but I do not have much knowledge of AI. I have a good knowledge of Java and I am currently working on a GSoC 16 project with Systers as my mentoring organisation.

**Comment by ctjoreilly** [comment]
@yatna I have sent you a direct email with some suggestions.

Best

Ciaran
