### ISSUE TITLE
Where can I get help? (CNF Problem)

### ISSUE THREAD

**Issue by peshav** [aimacode/aima-java#233]
Hello guys!

First I'd like to say thanks for providing this great libary.

However I can't figure out how to convert my term into an cnf expression.

Term:
(a && !b) || (c && !b) || (a && b) || (c && b) || (d)

Can you help me out? Also sorry if I'm posting this at the wrong place.

Thanks!
Peter

**Comment by ctjoreilly** [comment]
For AIMA3e, this should help:

https://github.com/aimacode/aima-java/blob/AIMA3e/aima-core/src/test/java/aima/test/core/unit/logic/propositional/visitors/ConvertToCNFTest.java

You will likely need to modify the syntax of the sentence you are using to work with the aima-java library (e.g. single '&' instead of '&&') . Let me know if that works for you.

Best

Ciaran

**Comment by ctjoreilly** [comment]
http://logic.stanford.edu/intrologic/applications/converter.html
should also help.
