### ISSUE TITLE
Add implementation of - Fig  6.11 Tree-CSP-Solver

### ISSUE THREAD

**Issue by GoogleCodeExporter** [aimacode/aima-java#30]
```
Fig  6.11 Tree-CSP-Solver.


```

Original issue reported on code.google.com by `ctjoreilly@gmail.com` on 23 Oct 2009 at 2:40

**Comment by anurag-rai** [comment]
I have structured the skeleton code of the solution and have sent a pull request.
To proceed further, I would like to know how to implement makeArcConsistent. Should it's implementation resemble the "revise" method of "AC3Strategy" class?
Also, since we're dealing with a List of Variables, would it be efficient to create another Array/List that points to the index of the parent in the List?

**Comment by ctjoreilly** [comment]
After a quick scan this looks like a good start to tackling this issue. I'll try look at in detail over the next few days. However, initially don't worry about optimizing the code. Focus on getting a basic version working that follows the pseudo-code in the book closely and also create a JUnit test driver (should not generate any system.out or system.err output) showing the implemented algorithm functioning. This simplifies evaluating the implementation.

**Comment by anurag-rai** [comment]
I have submitted a pull request for the complete solution to resolve this issue. 
The code along with the test-cases are working.

**Comment by ctjoreilly** [comment]
Thanks, I'll try look at in detail over the coming few days.

**Comment by smsubham** [comment]
Is this issue still open?

**Comment by anurag-rai** [comment]
It is. But I'm already working on it and a patch has been submitted
