### ISSUE TITLE
Add implementation of - Fig 13.1  DT-Agent

### ISSUE THREAD

**Issue by GoogleCodeExporter** [aimacode/aima-java#37]
```
Fig 13.1  DT-Agent


```

Original issue reported on code.google.com by `ctjoreilly@gmail.com` on 23 Oct 2009 at 2:51

**Comment by mshubhankar** [comment]
How are inputs to be made (the possible outcomes and its probabilities) ?

**Comment by ctjoreilly** [comment]
I would probably approach this like the 7.1 KB-Agent, whereby it is an abstract base class showing the main structure of the agent's implementation. Instead of a Knowledge Base you would be using a Probability Model (though I don't think the current API has a way of assert the model with new facts). The percepts and actions are specific to an implementation and just need to be translated into the underlying model as facts. However, you can avoid these details in the abstract implementation.

**Comment by mshubhankar** [comment]
@ctjoreilly  I was stuck at implementing the persistent belief_state. Should i create another class for it with the getActions() and observe() function ? And where do i get the expected_outcome_utility of a belief state if i need to implement the same ?

**Comment by samagra14** [comment]
This issue is resolved. Hence closing this issue.
