### ISSUE TITLE
GraphPlan isn't returning the full correct solution for PlanningProblemFactory.airCargoTransportProblem

### ISSUE THREAD

**Issue by larrybehaviorlanguage** [aimacode/aima-java#484]
I am running the latest from aima3e, I can run Graphplan and all relevant unit tests succeed.

When I run it for PlanningProblemFactory.airCargoTransportProblem, the planner completes, but it returns a partial solution that is missing the "unload" action schemas.

I did a bit of digging and see that, when I run with this problem, extractSolution is called twice. In the first call, the unload actions are selected, but it then returns null after reaching this check:

```            
if (setToBeTaken == null) {
   nogoods.put(level, goalsCurr);
   return null;
}
```

The second call to extractSolution then completes planning, but the unload actions aren't included in the second call's solution so they're not in the returned solution list.

Should each extractSolution phase's solution list be concatenated into the subsequent phases?

**Comment by RuedigerLunde** [comment]
Thank you for your issue report! Yes, there was a bug. After extending the levels of the graph the algorithm lost the original goal. Method extractSolution modified the original goal instead of a copy when moving backwards through the levels of the graph.

Unfortunately, this is not the only bug. Instead of doing a search in the space of all possible combinations of actions, extractSolution just selects the first possible combination in each level. For the AirCargoTransportProblem, a correct solution is now luckily found, but it is not minimal. This problem will be harder to fix :-(

**Comment by RuedigerLunde** [comment]
The second problem should now also be fixed :-)

**Comment by larrybehaviorlanguage** [comment]
Thanks so much @RuedigerLunde! I pulled down the latest and confirmed it's working. I also see that the solution is now correctly ordered. I see that there are more problem test cases on the python side. Soon I'd like to test those in this project to confirm all are working. I can add them to PlanningProblemFactory and add some tests in GraphPlanAlgorithmTest.

**Comment by RuedigerLunde** [comment]
Great! More examples and tests are very welcome. I will also add a demo to the gui-subproject this weekend. Thank you!
