### ISSUE TITLE
Code duplication between adversarial search Game and framework classes

### ISSUE THREAD

**Issue by moshewe** [aimacode/aima-java#90]
Implementing Game requires to implement an "actions" functions and a "result" function separate from the interfaces defined in the Framework interfaces. Duplication can be avoided if the adversarial search classes reuse the interfaces in the framework package.

**Comment by ctjoreilly** [comment]
Will look to address as part of the AIMA4e branch work.

**Comment by BenK10** [comment]
How should this be handled? Here are the signatures for getActions and getResult from the Game interface: 
`List<ACTION> getActions(STATE state);`
`STATE getResult(STATE state, ACTION action);`

whereas the signatures for ActionsFunction and ResultFunction interfaces from search.framework are
`Set<Action> actions(Object s);` and
`Object result(Object s, Action a);`

So using the search framework's versions of these functions means code using the Game interface will have to change from using a List<Action> to a Set<ACTION>. It will also have to cast the Object parameters and returned Objects into States. There are problems with this:
1. casts are ugly
2. relying on the search framework's interface for Actions and Result means a game will now have to implement three interfaces rather than one: Game, ActionsFunction, and ResultFunction. This increases dependencies and makes the code less clear. 

So, is there a way to clean up this issue without introducing more/bigger problems than it solves?

**Comment by ctjoreilly** [comment]
Closing. On the aima4e branch the ActionsFunction and ResultFunction interfaces are now shared by Problem and Game.
