### ISSUE TITLE
Add sections to wiki providing coding and submission guidelines

### ISSUE THREAD

**Issue by ctjoreilly** [aimacode/aima-java#98]

**Comment by rangira** [comment]
Hello Everyone 

I am Rudrani Angira , a  Computer Science graduate student at Indiana University . I am highly interested to contribute in the codes for Artificial Intelligence as I am taking that course this semester and following the same textbook .
I was going through the open issues but I could not find any mailing list where I could discuss about how I can contribute . It would be really helpful if someone could please direct me to a mailing list so that I do not spam . 

Thanks 
Rudrani

**Comment by ctjoreilly** [comment]
Outside of the aima-talk yahoo group:

https://groups.yahoo.com/neo/groups/aima-talk/conversations/messages

There are no mailing lists used. GutHub's Issue tracking is how we plan to manage interests in specific topics or for people to submit suggestions.

Best

Ciaran

**Comment by smsubham** [comment]
Structure of project:
This project source code has two parts
1.  Implementation of Pseudo Code
2.  Writing Unit Test Using JUnit.
To  know more about JUnit refer to below links.
http://junit.org/junit4/
https://en.wikipedia.org/wiki/JUnit
Any submission made should ideally follow same Pseudo Code in the book as closely as possible.
Branches in project :
1.  AIMA2e : This branch is no longer supported. Release 0.95 is the final release based on the 2nd edition of the book.
2.  AIMA3e (Current Branch): Any code submitted in this branch should be compaitnle with JDK 7.  Some of its algorithms are yet to be implemented and any contribution will be appreciated.
3.  AIMA4e-Java (In progress) : This branch will consists of complete rewrite of programs from AIMA3e to reflect new features in JDK 8. This will also become the new master branch once the 4th edition of "Artificial Intelligence - A Modern Approach" is published.

Raising an Issue :
If you find any bug in this project or feel that something new should be added to make it better you can use this page to let us know about that by following below steps.
1.  Go to Issue page and click on New Issue

![issue](https://cloud.githubusercontent.com/assets/16716026/14412684/a99bd0c8-ff85-11e5-8e13-98cce4bb9556.PNG)

2.In title be specific of what this particular issue is related to. Be more descriptive about details of this issue in comment section. Then click 0n Submit new issue.

Submitting a Pull Request :
After you have solved some of issue you are required to submit a pull request s so that we can review your code in detail. 
1.To do this first fork our code (if not already done) and add the code you have written in required branch of forked code.
2. Then click on submit a new pull request.

![new pull](https://cloud.githubusercontent.com/assets/16716026/14412689/c96d8f4a-ff85-11e5-9a12-bd0a59b99520.PNG)

3.Then compare across forks and select the forks across which you want to compare.

![compare](https://cloud.githubusercontent.com/assets/16716026/14412709/226088fa-ff86-11e5-919b-e2df8ba6ad41.PNG)

4.Then commit and provide description of how you have solved this issue.

Mailing List :
This project has only one mailing list in Yahoo.
https://groups.yahoo.com/neo/groups/aima-talk/conversations/messages
@ctjoreilly

**Comment by Manthan-R-Sheth** [comment]
@ctjoreilly  This explanation by @smsubham can be very useful if added to the [Contributing](https://github.com/aimacode/aima-java/wiki/AIMAJava-Contributing) section of the repo's wiki page.

**Comment by ctjoreilly** [comment]
I have update the [Contributing](https://github.com/aimacode/aima-java/wiki/AIMAJava-Contributing) and [AIMA4e Overview](https://github.com/aimacode/aima-java/wiki/AIMA4e-Overview) to help address this.
